lib/tomo/runtime.rb
lib/tomo/runtime/no_tasks_error.rb
test/tomo/runtime_test.rb

If `.tomo/config.rb` is lacking a list of deploy or setup tasks and the user tries to run `tomo deploy` or `tomo setup`, display a useful message instead of "Deployed tomo to no hosts".

Show a helpful error message if deploy/setup is run and no tasks are configured

---

.circleci/config.yml

Open source projects get 4 free containers, so we can run more jobs at once to shorten overall build time.

Increase build parallelism in CircleCI

---

lib/tomo/runtime.rb
lib/tomo/testing/docker_image.rb
lib/tomo/testing/local.rb
test/rails_setup_deploy_e2e_test.rb
test/tomo/cli/completions_test.rb
test/tomo/runtime_test.rb

In order to determine completions, `DeployOptions` creates a hypothetical (empty) execution plan in order to compute the full list of settings. A recent change added an assertion that prevents empty execution plans, thus breaking the completions.
Fix by restoring the ability to create empty execution plans.
Also: In some cases when testing locally the test can attempt to open a connection to the docker container before the sshd process in the container is ready. Work around this by adding a slight delay after the starting the docker container.

Fix a bug where bash completions were not working for deploy/run/setup options

---

lib/tomo/plugin/core.rb
lib/tomo/runtime/task_runner.rb
lib/tomo/ssh.rb
lib/tomo/ssh/options.rb

Before, you needed to pass an `SSH::Options` object into `SSH.connect`, and constructing `SSH::Options` required supplying a bunch of required values that had no defaults. That meant using `SSH.connect` outside of tomo's settings system was difficult.
With this commit the SSH API has been refactored such that `SSH.connect` now accepts a simple hash of options, not an opaque object, and there are reasonable default options such that this hash is completely optional. In the future, if tomo were to officially support a standalone SSH use case (sort of like SSHKit), this refactor makes the API much more approachable.

Refactor `SSH.connect` options for easier standalone use

---

docs/commands/run.md
lib/tomo/cli.rb
lib/tomo/cli/completions.rb
lib/tomo/commands/default.rb
lib/tomo/commands/run.rb
lib/tomo/testing/local.rb
test/rails_setup_deploy_e2e_test.rb
test/tomo/cli/completions_test.rb
test/tomo/cli_test.rb

Inspired by `yarn`, this PR modifies `Tomo::CLI` so that the `run` command is implied and can be omitted when running tasks from the command line. This syntax will also be familiar to rake users.
In other words, instead of:
```
$ tomo run rails:console
```
You can now write:
```
$ tomo rails:console
```
The existing `run` syntax will continue to be supported.

Introduce `tomo TASK` as a CLI shorthand for `tomo run TASK`

---

docs/plugins/bundler.md
lib/tomo/plugin/bundler/tasks.rb
test/tomo/plugin/bundler/tasks_test.rb

Normally `bundler:upgrade_bundler` guesses the version of bundler to install based on the contents of `Gemfile.lock`. However there are some scenarios, such as when you are preparing the remote host for a future deployment, where you might want to install a version other than the current version in the `Gemfile.lock`.
This PR facilitates this by making it possible to specify the desired version of bundler on the command like when using `tomo run`, like this:
```
$ tomo run bundler:upgrade_bundler 2.0.2
```

Allow `bundler:upgrade_bundler` to accept a CLI arg with the desired bundler version

---

lib/tomo/commands/default.rb
test/tomo/cli/completions_test.rb

Before, `tomo run TASK` would offer bash completions for the TASK argument, but this did not work for `tomo TASK`.
This commit now makes it is possible to get bash completions once a `:` is typed and therefore tomo is able to guess that the user is typing a task name as opposed to another tomo command.
So for example:
```
$ tomo rails:<TAB>
assets_precompile   db_create           db_schema_load      db_setup            log_tail
console             db_migrate          db_seed             db_structure_load
```

Enable bash completions for new `tomo TASK` CLI style

---

lib/tomo/cli.rb
lib/tomo/cli/common_options.rb
lib/tomo/cli/completions.rb
lib/tomo/commands/default.rb
lib/tomo/commands/init.rb
lib/tomo/ssh/connection.rb
lib/tomo/testing.rb
lib/tomo/testing/cli_extensions.rb
lib/tomo/testing/cli_tester.rb
lib/tomo/testing/local.rb
lib/tomo/testing/log_capturing.rb
lib/tomo/testing/mocked_exit_error.rb
lib/tomo/testing/plugin_tester.rb
test/tomo/cli/completions_test.rb
test/tomo/cli_test.rb

Before, there was no "official" way to write CLI tests, but the few we had involved running tomo via `bundle exec tomo` in a completely separate process and capturing the output. This is awkward and slow. Why not just invoke the `CLI#run` method directly and test that way?
Turns out it is not that easy, because among other things, the CLI might call `Process.exit`, killing the entire test harness.
This PR makes CLI testing easy (and about 2x faster than `bundle exec tomo`) by introducing a `CLITester` helper class. This class handles:
* capturing output for easy inspection after the CLI has run
* gracefully handling when the CLI exits
* restoring any global variables that were altered by the CLI so that other tests aren't affected
To make this possible, any direct uses of `Process.exit` …

Make CLI tests faster and easier to write

---

docs/plugins/bundler.md
lib/tomo/plugin/bundler.rb
lib/tomo/plugin/bundler/tasks.rb
test/tomo/plugin/bundler/tasks_test.rb

Before, the `bundler:upgrade_bundler` task would work by checking the `Gemfile.lock` to determine the version of bundler to install. Sometimes we want to specify the version explicitly instead of relying on this magic.
In an earlier commit, support for manually specifying a bundler version was done via a command-line argument, but this is not consistent with other tomo plugins. Other plugins like nvm and rbenv have a setting that controls the version. The nice thing about this is settings also work on the command line via the `-s` option, so it is a nice solution that supports both styles.
This commit adds a `:bundler_version` setting for this purpose. If the setting is `nil` (the default), it falls back to the auto-detect behavior that existed previously. For consistency, the `:run_args` …

Allow bundler version to specified via setting

---

docs/plugins/puma.md
lib/tomo/plugin/puma.rb
lib/tomo/plugin/puma/tasks.rb
test/tomo/plugin/puma/tasks_test.rb

Puma 4.1.0 no longer flushes stdout before daemonizing. This causes tomo to hang indefinitely after calling `puma --daemon` because the SSH connection does not cleanly exit.
Fix by explicitly redirecting stdout and stderr to files. This has an added benefit of storing troubleshooting information in cases where puma fails to start for other reasons.

Fix hang when starting puma 4.1.0

---

lib/tomo/templates/config.rb.erb

Starting in Rails 6.0.0, the puma configuration that ships with Rails assumes that the `tmp/pids` directory exists. This is not the case with a default deploy.
Support Rails 6 by linking `tmp/cache`, `tmp/pids`, and `tmp/sockets` by default, so these directories are guaranteed to exist and are shared between releases.

Link directories needed by puma (Rails 6 support)

---

lib/tomo/templates/config.rb.erb

Most simple deploys of Rails do not involve Nginx/Apache, and therefore files in `public/` (including CSS and JS) will not be served unless `RAILS_SERVE_STATIC_FILES` is enabled.
This commit enables this env var by default for new tomo projects.

Enable RAILS_SERVE_STATIC_FILES by default

---

lib/tomo/paths.rb
test/tomo/paths_test.rb

Before, if a path setting was `nil`, accessing that setting via the `paths` DSL would return an empty string, which is inconsistent. Now the DSL will also return `nil` in that scenario.

Handle nil path settings more consistently

---

docs/plugins/git.md
lib/tomo/plugin/core/tasks.rb
lib/tomo/plugin/git.rb
lib/tomo/plugin/git/tasks.rb
test/tomo/plugin/core/tasks_test.rb
test/tomo/plugin/git/tasks_test.rb

In a CI situation, you will want to deploy the commit that was just tested by CI, rather than a branch name which may point to a different commit.
For example consider the situation where a developer pushes commit A to master and the CI build starts. A few seconds later another developer pushes commit B to master. The CI build for commit A is successful and triggers a deploy via tomo. However since tomo deploys whatever is on master, that means commit B will actually get deployed, even though it hasn't been tested yet by CI.
This PR adds a new setting called `:git_ref` that can be used to tell tomo to deploy a specific commit, like this:
```
$ tomo deploy -s git_ref=a944898
```
If `:git_ref` is specified it overrides the `:git_branch` setting.
Note that `:git_ref` and `:git_branch` …

Add :git_ref setting to allow deploying an arbitrary SHA/tag

---

docs/commands/setup.md
docs/configuration.md
docs/plugins/bundler.md
lib/tomo/plugin/bundler.rb
lib/tomo/plugin/bundler/tasks.rb
lib/tomo/templates/config.rb.erb
test/tomo/plugin/bundler/tasks_test.rb

Starting with bundler 2.1, flags like `--path` are deprecated for the `bundle check` and `bundle install` commands. [In bundler 3.0 these flags will be dropped altogether.](https://github.com/bundler/bundler/blob/v2.1.0.pre.1/UPGRADING.md#cli-deprecations) That means the preferred way to configure the behavior of bundler going forward is to use either environment variables or a `.bundle/config` file.
This commit changes how tomo uses bundler to be forward-compatible with bundler 3.0.  Now, instead of passing flags to `bundle install`, tomo has a new task called `bundler:config` that will write an appropriate `.bundle/config` file based on the various `:bundler_*` tomo settings.
This is a breaking change due to the following:
1. The general-purpose `:bundler_install_flags` setting has been …

Explicitly configure bundler with a .bundle/config file rather than relying on side effects of bundle install flags (Bundler 3 support)

---

README.md
docs/plugins/puma.md
lib/tomo/plugin/puma/tasks.rb
test/tomo/plugin/puma/tasks_test.rb

Puma 4.1.0 had a bug (https://github.com/puma/puma/issues/1906) where its output was not properly detached prior to daemonizing. To work around this, I added output redirection to the `bundle exec puma` command to force the output to be detached from the console (see #39).
Now that puma has fixed this bug, I am removing the output redirection. The redirection had a downside: it hid messages from the console that were valuable for troubleshooting. For example if puma had an invalid config file that prevented it from starting, the error would have been hidden.
To avoid a breaking change, I am keeping the `:puma_stdout_path` and `:puma_stderr_path` tomo settings around. But rather than using them for output direction, they will be passed to puma's `--redirect-stdout` and `--redirect-stderr` …

Revert workaround for puma 4.1.0 output bug

---

docs/api/TaskLibrary.md
docs/plugins/core.md
docs/tutorials/writing-custom-tasks.md
lib/tomo.rb
lib/tomo/configuration.rb
lib/tomo/plugin/core.rb
lib/tomo/plugin/core/helpers.rb
lib/tomo/remote.rb
lib/tomo/runtime.rb
lib/tomo/runtime/template_not_found_error.rb
lib/tomo/task_api.rb
lib/tomo/task_library.rb
test/fixtures/template.erb
test/tomo/plugin/core/helpers_test.rb
test/tomo/task_api_test.rb

The PR enhances the `write` helper such that it now optionally accepts a `template:` keyword argument instead of `text:`. If `template:` is specified, merge the given template (a local path to an ERB template file) and write the resulting text to the remote location.
For example:
```ruby
remote.write template: File.expand_path("unicorn.service.erb", __dir__),
to: ".config/systemd/user/unicorn.service"
```
For tasks that wish to deal with templates directly, this PR also introduces a `merge_template` method that loads an ERB template from a specified path and merges it.
Both `write template:` and `merge_template` follow this behavior:
- If the template path starts with a `"."`, treat it as relative to the tomo config directory
- The ERB template can access `settings`, `paths`, `remote`, …

Add support for ERB templates

---

docs/plugins/puma.md
lib/tomo/plugin/puma/tasks.rb
test/tomo/plugin/puma/tasks_test.rb

Example output:
```
$ tomo run puma:status
tomo run v0.10.0
→ Connecting to deployer@app.example.com
• puma:status
systemctl --user status puma_example.socket puma_example.service
● puma_example.socket - Puma HTTP Server Accept Sockets for example
Loaded: loaded (/home/deployer/.config/systemd/user/puma_example.socket; enabled; vendor preset: enabled)
Active: active (running) since Thu 2019-10-24 09:41:53 UTC; 1 weeks 2 days ago
Listen: 0.0.0.0:3000 (Stream)
● puma_example.service - Puma HTTP Server for example
Loaded: loaded (/home/deployer/.config/systemd/user/puma_example.service; enabled; vendor preset: enabled)
Active: active (running) since Fri 2019-11-01 15:46:10 UTC; 1 day 10h ago
Main PID: 14513 (bundle)
CGroup: /user.slice/user-1000.slice/user@1000.service/puma_example.service …
```

Add puma:status task that reports systemd status

---

lib/tomo/cli/command.rb

Currently there are problems with `def_delegators` in Ruby 2.7 with respect to keyword arguments. This causes warnings like:
```
ruby/2.7.0/forwardable.rb:235: warning: The last argument is used as the keyword parameter
```
Work around this in tomo by not using `def_delegators` in some cases.

Fix keyword parameter warnings in Ruby 2.7

---

lib/tomo/remote.rb

This was causing a warning in Ruby 2.7:
```
tomo/remote.rb:25: warning: The last argument is used as the keyword parameter
tomo/script.rb:5: warning: for `initialize' defined here
```

Fix misused double-splat that caused warning in Ruby 2.7

---

lib/tomo/templates/config.rb.erb

We are using systemd for puma, and systemd has a robust logging system built in. To take advantage of this, Rails has to be configured to send its output to stdout. This is something that Rails supports out of the box via the `RAILS_LOG_TO_STDOUT` environment variable.
Recommend tomo users set this by putting it in the default config file that is generated by `tomo init`.

Send Rails logs to stdout by default

---

lib/tomo/runtime/settings_interpolation.rb
test/tomo/runtime/settings_interpolation_test.rb

The `%<...>` syntax was deprecated in tomo 0.9.0. This PR removes this syntax entirely in favor of the newer `%{...}` syntax.
From #59 :
---
Tomo used to use `%<setting_name>` for string interpolation within settings, in order to allow composition of settings like:
```ruby
set application: "my-app"
set deploy_to: "/var/www/%<application>"
```
That worked great but it went against the grain for how `%<...>` is normally used in Ruby. In Ruby, string formatting (i.e. interpolation) is done in one of three ways:
```ruby
format("/var/www/%s", "my-app")
format("/var/www/%<application>s", application: "my-app")
format("/var/www/%{application}", application: "my-app")
```
Notice that in Ruby's [Kernel#format](https://ruby-doc.org/core-2.6.5/Kernel.html#method-i-format), the angle bracket style …

Remove support for deprecated %<...> syntax

---

lib/tomo/runtime/unknown_task_error.rb
test/tomo/cli_test.rb

If you try to run a task but the namespace of the task is not recognized, tomo will now helpfully suggest that you may need to load the plugin that defines that namespace. E.g.
```
$ tomo run sidekiq:setup
tomo run v0.12.0
ERROR: sidekiq:setup is not a recognized task.
To see a list of all available tasks, run tomo tasks.
Did you forget to install the sidekiq plugin?
```

Show friendly error when plugin is missing

---

docs/commands/deploy.md
docs/configuration.md
lib/tomo/commands/deploy.rb
lib/tomo/runtime.rb
lib/tomo/runtime/execution_plan.rb
lib/tomo/runtime/explanation.rb
lib/tomo/runtime/host_execution_step.rb
test/tomo/runtime/execution_plan_test.rb

One of the tricker parts of tomo's implementation is how it translates a configuration into an "execution plan" that automatically connects to appropriate hosts and schedules tasks onto a thread pool for running on many hosts at once.
This PR gives users the ability to ask tomo for an "explanation" of this execution plan by passing `--debug` option to `tomo deploy` (or `run` or `setup`). This can come in handy for troubleshooting more complex deployments that involve multiple hosts, roles, and task batches.
Here is an example explanation for a deployment that has 2 hosts, batches, and a "db" role:
```
CONCURRENTLY (2 THREADS):
= CONNECT deployer@app1.example.com
= CONNECT deployer@app2.example.com
CONCURRENTLY (2 THREADS):
= IN SEQUENCE:
RUN env:update ON deployer@app1.example.com
RUN …
```

Describe execution plan when --debug is used

---

lib/tomo/templates/config.rb.erb

The official webpacker deployment documentation recommends that `public/packs` and `node_modudles` be included in `linked_dirs`, so that webpack compilation does not have be redone from scratch for every release.
https://github.com/rails/webpacker/blob/master/docs/deployment.md
We already link `node_modules` but `public/packs` was missing. This commit adds it to the default `linked_dirs` generated by `tomo init` so that it is included in new tomo projects going forward.

Include `public/packs` in linked_dirs for better webpacker support

---

lib/tomo/console.rb
lib/tomo/console/key_reader.rb
lib/tomo/console/menu.rb
test/tomo/console_test.rb

CI is by definition an non-interactive environment. However, before, tomo was not able to detect this reliably. As a result, if a tomo deploy used something like `Console.prompt` or `Console.menu`, this would crash or hang indefinitely.
This commit improves how non-interactive environments are detected so that tomo exits with a more descriptive error instead of hanging.
- Use env vars to detect whether tomo is running in CI.
- Treat CI environment as non-interactive.
- Console.prompt will now explicitly raise instead of crashing on `nil`.
- Refactor Tomo::Console into a singleton class to facilitate testing.
- Add test coverage.

Improve console detection; treat CI as non-interactive

---

lib/tomo/console.rb
lib/tomo/console/non_interactive_error.rb
lib/tomo/plugin/env/tasks.rb

This PR makes some usability improvements to the `env:update` task:
- Explain why tomo is prompting for a value
- Don't show a giant stack trace if prompting fails due to a non-interactive console.
For example, let's say tomo is running a deploy in a CI environment, and the `env:update` task fails because a required environment variable is missing and an interactive console is needed.
Before, the user would see a stack trace with a message that an interactive console was needed, but not _why_ it was needed.
Now the error is much more concise and there is an explanation of why tomo needs an interactive console:
```
$ tomo deploy
tomo deploy v0.17.0
→ Connecting to deployer@app.example.com
• env:update
The remote host needs a value for the $FOO environment variable.
Please provide a value …
```

Improve env:update output and error handling

---

docs/tutorials/publishing-a-plugin.md

The [tomo-plugin](https://github.com/mattbrictson/tomo-plugin/) GitHub template now uses `require_relative`. Update the documentation to match.

Update plugin tutorial to match latest template

---

docs/css/extra.css

- Don't wrap `<code>` inside table cells

Further fixes for styles broken by mkdocs 1.1

---

docs/plugins/bundler.md
lib/tomo/plugin/bundler/tasks.rb
test/tomo/plugin/bundler/tasks_test.rb

If `:bundler_version` is not specified, tomo will try to guess the desired version by extracting the `BUNDLED WITH` value from the `Gemfile.lock`.
Before, if this fails (e.g. because the lock file is missing), the `bundler:upgrade_bundler` task would silently do nothing. This is surprising because no other tomo task behaves like this.
Now, `bundler:upgrade_bundler` will fail with a helpful error message if the bundler version cannot be determined. If you do not want to use tomo to manage the installation of bundler, it is easy to just remove the `bundler:upgrade_bundler` from the list of setup tasks instead of having it fail silently.

Fail loudly if tomo cannot guess bundler version

---

lib/tomo/plugin/puma/systemd/service.erb

We install puma as a user-level systemd service. For user-level services, `WantedBy=multi-user.target` does not do anything. That meant that puma would not get started automatically on boot. Socket activation means that puma would still start automatically the first time an HTTP request was received, but this first request would be slow.
Fix by changing to `WantedBy=default.target`. Now puma will start eagerly on boot, ensuring a fast response the first time an HTTP request is received.
To take advantage of this new behavior, re-run:
```
$ tomo run puma:setup_systemd
```

Ensure puma starts eagerly on system boot

---

lib/tomo/plugin/env/tasks.rb
test/tomo/plugin/env/tasks_test.rb

Fix NoMethodError in env:setup when env_vars contains an integer

---

lib/tomo/plugin/rails/helpers.rb
test/tomo/plugin/rails/helpers_test.rb

The documentation for tomo's `rake` helper, and the intent of that method, is that it runs `bundle exec rake`. However this `rake` helper was in fact running `bundle exec rails` instead. This was a mistake.
Fix this so that the `rake` helper, and tasks that depend on it (e.g. `rails:db_migrate`, `rails:db_seed`, etc.) use `bundle exec rake` instead of `bundle exec rails` as originally intended.
This also makes tomo compatible with older versions of Rails, before the `rails` was smart enough to be able to invoke rake tasks.

Use rake to invoke rake tasks, not rails

---

lib/tomo/shell_builder.rb
test/tomo/shell_builder_test.rb

Before, if `raw` was passed a frozen string it would raise an exception:
```
TypeError (can't define singleton)
```
This commit fixes the problem by making a copy of the original string before attempting to extend it.

Fix TypeError when using raw helper with a frozen string

---

lib/tomo/plugin/bundler/tasks.rb

Before, running a setup with `--dry-run` would fail with this error:
```
* • bundler:upgrade_bundler
* tail -n 10 /tmp/tomo/20200706205321/Gemfile.lock
ERROR: The bundler:upgrade_bundler task failed on user@hostname.or.ip.address.
Could not guess bundler version from Gemfile.lock.
Use the :bundler_version setting to specify the version of bundler to install.
```
This commit allows the dry-run to succeed even if `bundler_version` is not explicitly set.

Fix error that would cause dry-run of `bundler:upgrade_bundler` to fail

---

lib/tomo/commands/init.rb
lib/tomo/templates/config.rb.erb

Tomo relies on `%{...}` syntax for interpolating settings. However, the default configuration for rubocop flags this syntax as a problem and suggests an alternative that doesn't work with tomo.
To prevent confusion, `tomo init` will now automatically include a special comment to disable the `Style/FormatStringToken` rule if it detects that rubocop is present.

Auto-disable `Style/FormatStringToken` rule in `.tomo/config.rb` if rubocop is present

---

Gemfile
tomo.gemspec

- Place development dependencies in the `Gemfile`, not the `.gemspec`
- Do not modify the `$LOAD_PATH` in the `.gemspec`
- Use `Gem::Requirement.new` to specify Ruby requirement
- Do not include `bundler` as a development dependency
- Reformat to a line length of 120

Adopt latest `Gemfile` and `.gemspec` standards

---

lib/tomo/plugin/env/tasks.rb
test/tomo/plugin/env/tasks_test.rb

There is a fundamental assumption in the tomo "env" tasks that only one application is being deployed to a given user@host. Some users have reported being confused and surprised when they deploy more than one app to the same user@host and things begin behaving strangely.
This limitation is documented in tomo's FAQ, but it would be even better if tomo would alert users earlier in the setup process before the second app is deployed and things start going sideways.
This commit modifies the `env:setup` task so that it is able to detect when a second app is being deployed to the same user@host. When this situation is detected it will halt the setup process with a detailed error message like this:
```
tomo run v1.2.0
→ Connecting to deployer@app.example.com
• env:setup
cat .bashrc
ERROR: The …
```

Prevent multiple apps from sharing the same bashrc

---

test/tomo/console_test.rb

These tests weren't running because the test methods were missing the `test_` prefix. Update them so that the tests actually run and fix the failures.

Fix console tests that were silently failing

---

test/support/reporters.rb

Tomo has quite a few tests now and the spec reporter we were using before produced many screen-fulls of output. Sometimes that made it hard to pinpoint failures. When running locally, use a more compact format to fix this.

Use a more compact minitest reporter locally

---

lib/tomo/console.rb
test/tomo/console_test.rb

Inject a dummy for stdout into `Tomo::Console` during tests so that it doesn't print directly to the real stdout. This cleans up test output so it is easier to keep track of pass/fail status.

Remove "Are you sure?" output when running tests

---

.circleci/config.yml
.travis.yml
Rakefile

CircleCI is faster and more reliable than Travis in my experience. We can't use CircleCI for every test, because it lacks an easy way to use ruby-head. However for every other version of Ruby, we can use matrix parameters in CircleCI to run our unit tests, rather than Travis.

Use CircleCI instead of Travis for testing older Ruby versions

---

lib/tomo/testing/docker_image.rb

The latest version of Docker (installed via the docker-edge homebrew cask) changes how the image ID is returned from the `docker build` command. This causes tomo's docker tests to break.
Fix by explicitly tagging the image that is being built rather than trying to parse the image ID from the `docker build` output.

Explicitly tag image to fix test failures with new Docker version

---

README.md
docs/comparisons.md

- Edits for brevity
- Show capistrano and tomo sample code side by side
- Add "protips" to the README for interesting things that are otherwise hard to find
- Add links throughout README to launch into reference docs for more detail
- Lean into tomo's robust Rails support and extensibility

Clean up README and comparisons document

---

docs/plugins/rbenv.md
lib/tomo/plugin/rbenv/tasks.rb
lib/tomo/templates/config.rb.erb

Make `rbenv_ruby_version` setting optional in favor of reading the value from `.ruby-version` file.
references #186

Autodetect rbenv_ruby_version via .ruby-version file

---

lib/tomo/commands/init.rb
lib/tomo/templates/config.rb.erb

If a project lacks a `.ruby-version` file, then `tomo setup` will fail if `rbenv_ruby_version` is not explicitly specified. Currently tomo does not include a `rbenv_ruby_version` setting in the default `.tomo/config.rb` file.
We can make the user's life a lot easier in this scenario by providing a default value when they initialize tomo.
This commit enhances `tomo init` so that if a `.ruby-version` is not present, tomo will include a `set rbenv_ruby_version: ...` setting in the generated `.tomo/config.rb` based on the currently executing version of Ruby.

Generate config.rb with explicit Ruby version, if needed

---

mkdocs.yml

The default for mkdocs is `edit/master/docs/` which yields a 404 for this repo. Update the config to use `edit/main/docs/`, which works.

Fix broken "edit on GitHub" links

---

docs/commands/setup.md
docs/plugins/core.md
lib/tomo/plugin/core.rb

`tomo setup` used to stage files in `/tmp/tomo`, which is a stable and predictable path. Since `/tmp` is globally writable, this path could be exploited by another process to interfere with the `tomo setup` command.
To prevent this, tomo will now use a randomly generated temporary path, like this: `/tmp/tomo-a4DBHX0P`.
If you prefer the old behavior, or wish to use a different path, set the `tmp_path` in your tomo config, like this:
```ruby
set tmp_path: "/tmp/tomo"
```

Randomize tmp_path for more security

---

lib/tomo/commands/init.rb
lib/tomo/templates/config.rb.erb

`tomo init` looks for the presence of a `.ruby-version` file. If that file exists, then the `.tomo/config.rb` file will omit an explicit setting for `:rbenv_ruby_version`. That's because tomo assumes it will be able to auto-detect the version at setup time.
However, if `.ruby-version` contains bad data, or a value that rbenv doesn't understand, that means that the user will be in for an unpleasant surprise: `tomo setup` will fail because it tries to guess the `:rbenv_ruby_version` from the `.ruby-version` file, and fails.
This commit fixes this problem with the following solution:
`tomo init` will omit the `:rbenv_ruby_version` setting only if the `.ruby-version` file contains an actual Ruby version number and that version number matches `RUBY_VERSION`. That way the auto-detection should …

Gracefully handle non-standard .ruby-version files

---

lib/tomo/configuration/unknown_plugin_error.rb

If a user installs tomo and tomo plugins via a Gemfile, but then runs tomo without using `bundle exec`, this can lead to errors like this:
```
ERROR: sidekiq is not a recognized plugin.
You may need to install the tomo-plugin-sidekiq gem.
```
This is because the plugins in the Gemfile are not available when tomo is run without `bundle exec`.
Until now, tomo's error message doesn't really make this clear.
This commit improves the error message so that it now says:
```
ERROR: sidekiq is not a recognized plugin.
You may need to install the tomo-plugin-sidekiq gem.
Try prefixing the tomo command with bundle exec to fix this error.
```
tomo will only suggest `bundle exec` if it is fairly certain that it will fix the error: there is a Gemfile present and it contains a `gem` entry for the …

Suggest `bundle exec` to fix missing plugin errors

---

lib/tomo/plugin/rbenv/tasks.rb

The rbenv-installer project has changed the location of its installation script to:
https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
Update tomo's `rbenv:install` task to match.
This fixes a bug where tomo would fail to install ruby with an error like this:
bash: rbenv: command not found

Fix failing `rbenv:install` task `rbenv: command not found`

---

Rakefile
docs/plugins/puma.md
lib/tomo/plugin/nodenv/tasks.rb

Many projects are in the process of renaming the default branch of their repositories. Rather than point to the default branch by name (e.g. `master`), use `HEAD` so that URLs will continue to work even if the branch is renamed in the future.

Switch to more stable GitHub URLs for docs, nodenv

---

docs/plugins/nodenv.md
lib/tomo/plugin/nodenv.rb
lib/tomo/plugin/nodenv/tasks.rb
lib/tomo/templates/config.rb.erb
test/tomo/plugin/nodenv/tasks_test.rb

Apps that use yarn v2 or v3 follow a pattern like this:
- Yarn v1 (legacy) is installed globally
- The desired version of yarn (2.x or 3.x) is packaged in the app itself, in `.yarn/releases`
Furthermore:
- `node_modules` is no longer the basis for caching downloaded node packages
- The default cache location is `.yarn/cache` within the project directory
This PR makes some minor tweaks to tomo to support yarn v2+ without breaking existing yarn v1 apps.
**Link yarn v2 cache directory for faster deploys.** In yarn v2 and later, yarn places its cache in `.yarn/cache` of the project directory by default. Linking `node_modules` is not sufficient for eliminating re-downloading of packages across deploys. To avoid re-downloads, we need to link the cache directory.
**Allow yarn to be installed …

Add automatic support for yarn v2+

---

lib/tomo/templates/config.rb.erb

The `bootsnap` gem is commonly used in Rails apps to improve boot performance. Part of its approach is to create caches for locating gems. These caches are by default stored in `tmp/cache`.
Out of the box, tomo links `tmp/cache` to its shared area. This means that the cache is shared and reused for every tomo release.
This sounds desirable, but in practice it is problematic. There is no way to clean the bootsnap cache, so every time a new gem or gem version is added to an app, the cache grows. Over the lifetime of a project, this accumulation can become significant.
More seriously, the bootsnap cache is sensitive to the absolute path of the app that is being run. In tomo, each release is deployed to a unique directory name based on the timestamp of the release. That means that each tomo …

Use private cache location for bootsnap to avoid endless accumulation of data

---

docs/plugins/git.md
lib/tomo/plugin/git.rb
lib/tomo/plugin/git/tasks.rb
lib/tomo/templates/config.rb.erb
test/tomo/plugin/git/tasks_test.rb

Certain operations, like the `git pull` issued by the `rbenv` installer, require that the git client on the remote host is configured with a valid `user.name` and `user.email`.
Git will try to auto-detect values for these settings, but depending on the host, this may not always be possible.
When this auto-detection fails, tomo will fail with errors like this:
```
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address
```
Fix by introducing a new tomo task that runs during setup: `git:config`. This will explicitly set the `user.name` and `user.email` values, so that …

Ensure git is configured with a valid `user.name` and `user.email`

---

docs/plugins/nodenv.md
docs/plugins/rbenv.md
lib/tomo/commands/init.rb
lib/tomo/plugin/nodenv/tasks.rb
lib/tomo/templates/config.rb.erb
test/tomo/commands/init_test.rb
test/tomo/plugin/nodenv/tasks_test.rb

If the project being deployed with tomo has a `.node-version` file, the `nodenv:install` task can now infer the node version from that file. This means that the `nodenv_node_version` setting is no longer required.

Use node version from .node-version file, if present

---

docs/tutorials/deploying-rails-from-scratch.md

Rails 7 no longer ships with `bin/yarn` and yarn is not required to deploy the default app created by `rails new`. So we don't need to mention it in the tutorial.

Remove mention of "bin/yarn" from Rails tutorial

---

requirements.txt

Fixes:
> Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_truly_sane_lists".

Pin markdown to work around mkdocs error

---

lib/tomo/path.rb
lib/tomo/ssh/child_process.rb
lib/tomo/testing/log_capturing.rb
test/tomo/console_test.rb

In instances when tomo is used without a Gemfile, or is used with a Gemfile that contains very few gems, running `tomo` might result in an "uninitialized constant" crash for `StringIO` or `SimpleDelegator`.
This happens because tomo is trying to use these constants without explicitly `require`-ing them. By luck, gems in a typical Gemfile will already require these, so by the time tomo runs, they have already been loaded. But this is not guaranteed.
Fix by using the proper `require` statements to insure that these constants are loaded.

Fix "uninitialized constant" errors for StringIO and SimpleDelegator

---

lib/tomo/templates/config.rb.erb

[vite_rails](https://vite-ruby.netlify.app) hooks into `assets:precompile`, so it will already work fine with tomo's default deploy script. This commit adds `public/vite` to the default list of `linked_dirs` to make deploys faster, by allowing the output of vite's build to be reused across releases.

Link `public/vite` by default for better `vite_rails` support

---

docs/plugins/rails.md
lib/tomo/plugin/rails/helpers.rb
test/tomo/plugin/rails/helpers_test.rb

[Thor](https://github.com/rails/thor) is an alternative to rake for writing command-line scripts in Ruby. It is built into Rails and maintained under the Rails GitHub organization.
In a Rails project, you can place `.thor` files under `lib/tasks/` (for example). Similar to Rake, you can run `thor -T` to see a list of commands, and `thor COMMAND` to run a command defined in one your `.thor` files.
Thor offers a more intuitive programming model compared to rake, and has a more full-featured set of CLI options parsing capabilities. Most importantly, while rake tasks are notoriously tricky to unit test and require boilerplate to do so, thor commands can be unit tested like plain ruby methods.
This PR adds a `remote.thor` helper to tomo (similar to `remote.rake`) so that developers who are …

Add helper for running thor tasks with `remote.thor`

---

lib/tomo/cli.rb
lib/tomo/commands/tasks.rb
test/tomo/cli_test.rb

This makes tomo behave similarly to `rake -T`, `cap -T`, and `thor -T`.

Add `tomo -T` as an alias for `tomo tasks`

---

docs/tutorials/deploying-rails-from-scratch.md
lib/tomo/testing/ubuntu_setup.sh

Compiling Ruby on Ubuntu in some cases requires libyaml-dev.

Add libyaml-dev to Ubuntu recommended packages

---

lib/tomo/plugin/rbenv/tasks.rb
test/tomo/plugin/rbenv/tasks_test.rb

When a pre-release version of Ruby is already installed, e.g. 3.2.0-rc1, tomo would fail to install the final version (3.2.0) with the misleading message, "Ruby 3.2.0 is already installed".
Fix by using a more robust regular expression to detect existing versions, and add unit tests.

Fix erroneous "Ruby <VERSION> is already installed" message

---

docs/tutorials/deploying-rails-from-scratch.md
lib/tomo/templates/config.rb.erb
lib/tomo/testing/ubuntu_setup.sh

- Building Ruby 3.2 with YJIT support requires the `rustc` package
- YJIT can be enabled by setting the `RUBY_YJIT_ENABLE=1` env var
This commit also adds all other Ubuntu packages recommended by the ruby-build documentation.

Enable Ruby 3.2's YJIT by default for new projects

---

lib/tomo/plugin/rbenv/tasks.rb
test/tomo/plugin/rbenv/tasks_test.rb

- Now the ruby build process will show output instead of appearing to be stuck for several minutes
- This output makes it easier to troubleshoot if compilation fails

Show verbose output when compiling Ruby

---

lib/tomo/testing/docker_image.rb
lib/tomo/testing/local.rb

`_TOMO_CONTAINER` was needed to get Docker working on Circle CI. After switching to Semaphore, this can now be removed.

Remove docker complexity no longer needed by CI

---

lib/tomo/plugin/nodenv/tasks.rb
lib/tomo/ssh.rb
lib/tomo/testing/host_extensions.rb
lib/tomo/testing/ssh_extensions.rb
test/tomo/plugin/nodenv/tasks_test.rb

When `nodenv:install` tries to guess what Node version to use, it attempts to read a `.node-version` file. This doesn't work in a `--dry-run`, because no SSH I/O occurs and the file is not actually read. As a result, a dry run would lead to this error:
> Could not guess node version from .node-version file.
Use the :nodenv_node_version setting to specify the version of node to install.
Fix by using a placeholder node version in the dry run scenario.
This PR introduces tomo's first dry-run unit test, so a little extra test support code was also added to make this type of test possible.

Fix bug where `nodenv:install` would fail during `--dry-run`

---

lib/tomo/plugin/env/tasks.rb
test/tomo/plugin/env/tasks_test.rb

Tomo stores environment variables (configured through the `env:` tasks) in an `envrc` file. Before this PR, that file had default permissions. On many systems, this could mean the file would be world-readable by any user by default.
This PR improves the security of tomo-managed environment variables by calling `chmod 600` when initially creating the `envrc` file.
For existing tomo deployments, you may want to manually check the permissions of the `envrc` file and change them if necessary.

Improve security of env variables by narrowing envrc permissions

---

docs/plugins/bundler.md
lib/tomo/plugin/bundler.rb
lib/tomo/plugin/bundler/tasks.rb
test/tomo/plugin/bundler/tasks_test.rb

When `bundle install` is run as part of the setup or deploy process, each gem has an opportunity to display a post-install message. These messages are mostly noise, especially for a deployment tool like tomo.
This PR changes the default bundler config that is generated by tomo to set the `BUNDLE_IGNORE_MESSAGES` option. This means that applications deployed by tomo will now hide gem post-install messages by default.
To adopt this new default, run the `bundler:setup` task to update the bundler config file:
```sh
tomo run bundler:setup
```
If you want to restore tomo's old behavior, and show post-install messages, then add this setting to your `.tomo/config.rb`:
```ruby
set bundler_ignore_messages: false
```
and then re-run `bundler:setup`.

Hide gem post-install messages by default

---

.github/workflows/ci.yml
lib/tomo/commands/init.rb
lib/tomo/templates/config.rb.erb
test/tomo/commands/init_test.rb

This PR improves how `tomo init` fills in the default `git_branch` value in the generated `.tomo/config.rb` file.
**Improved behavior on new, empty git repos**
Before, when `tomo init` was run on a brand new git repo that does not yet have any commits, a confusing message would be printed to stderr and tomo would fail to fill in the `git_branch` setting in the generated `.tomo/config.rb` file:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Now, `tomo init` will use the `git branch --show-current` command (available in git 2.22 and newer) to determine the current branch name. This command works even for a git repo that does not yet have any …

More reliably guess the right git_branch when generating .tomo/config.rb

---

lib/tomo/commands/init.rb
lib/tomo/templates/plugin.rb.erb
test/tomo/commands/init_test.rb

Before, `tomo init` would generate a sample plugin file, but that file was empty with no explanation. This PR adds a comment to the sample plugin file that `tomo init` generates, so that:
- Users know where to find more information about writing plugins
- Rubocop doesn't complain about the fact that the file is empty
This also fixes a `TODO` in `init.rb`.

Include doc link in sample plugin generated by `tomo init`

---

Gemfile
test/support/ci.rb
test/support/reporters.rb
test/test_helper.rb

- Remove `minitest-ci` since it is not used by GitHub Actions
- Remove `minitest-reporters` in favor of `minitest-rg`, which is simpler, is officially maintained by the minitest GitHub organization, and doesn't patch minitest internals in ways that can break other plugins
- Remove now unneeded `test/support` directory

Simplify test dependencies

---

tomo.gemspec

Fixes the following warning on Ruby 3.3.0:
> abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec.

Add abbrev dependency to fix warning on Ruby 3.3

---

lib/tomo/cli.rb
test/tomo/cli_test.rb
tomo.gemspec

Our use of the `abbrev` gem is simple enough that we can replace it with our own simple implementation. This eliminates the gem dependency so that tomo can continue to have "minimal dependencies", as advertised in the README.

Remove `abbrev` dependency

---

lib/tomo/templates/config.rb.erb

- `RACK_ENV` is not strictly needed; `RAILS_ENV` is enough
- `RAILS_LOG_TO_STDOUT` and `RAILS_SERVE_STATIC_ASSETS` are no longer used in newly generated Rails apps

Remove unnecessary env vars from suggested config

---

docs/plugins/env.md
docs/tutorials/deploying-rails-from-scratch.md
lib/tomo/plugin/env/tasks.rb
lib/tomo/templates/config.rb.erb
test/e2e/rails_setup_deploy_e2e_test.rb
test/tomo/plugin/env/tasks_test.rb

When specifying `:env_vars` in the tomo config file, you can now use a special `:generate_secret` value. This will automatically generate a secret using `SecureRandom.hex(64)` the first time it is needed.
The tomo configuration template created by `tomo init` now includes this env var value:
```
SECRET_KEY_BASE: :generate_secret
```
This means that the first time the app is deployed, an appropriate value for `SECRET_KEY_BASE` will be generated automatically, without prompting the user.

Auto-generate env var values, e.g for `SECRET_KEY_BASE`

---

lib/tomo/plugin/rbenv/tasks.rb
test/tomo/plugin/rbenv/tasks_test.rb

Recently, tomo's `rbenv:install` task has started failing with this output:
```
Installing ruby 3.3.0 -- this may take several minutes
CFLAGS=-O3 rbenv install 3.3.0 --verbose
bash: line 1: rbenv: command not found
```
This is because rbenv was recently updated[^1] to to automatically add the `rbenv init` script to the `.bashrc` file during installation.
However, rbenv adds it to the _bottom_ of the file after the early-exit that skips most of the `.bashrc` when it is sourced in a non-interactive shell (i.e. tomo via SSH).
That left rbenv in an installed but broken state; hence the error.
Fix by having `rbenv:install` detect this situation and prepend the `rbenv init` script to the _top_ of the file, where it will get loaded for non-interactive shells such as tomo's.
[^1]: …

Fix "rbenv: command not found" error when running `rbenv:install`

---

lib/tomo/configuration/dsl/batch_block.rb
lib/tomo/configuration/dsl/tasks_block.rb
lib/tomo/host.rb
lib/tomo/runtime.rb
test/tomo/configuration_test.rb

If the `.tomo/config.rb` file declares a setup or deploy task with `privileged: true` and the file starts with the special `# frozen_string_literal: true` comment, tomo crashes with the following error message:
```
TypeError: can't define singleton
lib/tomo/configuration/dsl/tasks_block.rb:17:in `extend_object'
lib/tomo/configuration/dsl/tasks_block.rb:17:in `extend'
lib/tomo/configuration/dsl/tasks_block.rb:17:in `run'
```
This is because tomo is trying to call `.extend` on a frozen string.
Fix by creating a mutable copy of task names before extending them.

Fix `TypeError` when `tomo/config.rb` uses frozen string literals

---

lib/tomo/console/key_reader.rb
test/tomo/console/key_reader_test.rb

When running `tomo deploy` in a multi-environment project with no environment explicitly specified, tomo prompts:
```
Choose an environment: 
❯ staging
production
```
Interacting with this menu with the keyboard would result in an error:
```
forwardable.rb:240:in 'String#clear': can't modify frozen String: "" (FrozenError)
from forwardable.rb:240:in 'Tomo::Console::KeyReader#clear'
```
This is because the internal `buffer` used by `KeyReader` was frozen as a side effect of #446.
Fix by marking `buffer` as mutable.

Fix `FrozenError` when using interactive environment selector

---

docs/plugins/puma.md
lib/tomo/plugin/puma/systemd/service.erb

Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
As discussed here => https://github.com/mattbrictson/tomo-plugin-sidekiq/pull/193

Resolve syslog obsolete warnings

---

lib/tomo/path.rb
test/tomo/path_test.rb

Fixes the following error when tomo is used on Ruby head:
```
TypeError: TypeError
vendor/bundle/ruby/3.5.0+3/gems/tomo-1.21.0/lib/tomo/path.rb:18:in 'Pathname#initialize'
vendor/bundle/ruby/3.5.0+3/gems/tomo-1.21.0/lib/tomo/path.rb:18:in 'Tomo::Path#dirname'
```

Fix TypeError on Ruby head in Tomo::Path
